# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e62edc477ba0266513aeb271f59d3a8fb9865ad766e3f00074f0589619fe8d39a6661372575ce95d56db273ddf188d2630d3fcd0de5487980d154050ac2591

test:
  secret_key_base: 18364ddabf39791e613c1ee5e16c5c161afc0d846befb9a766d29a9c4b52461ae92e6ec7728717809b462e54348a0ab6c7ca521ae90c97306fdf28fd14b42ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
